// Description:
// Garage info for UCF Campus


module.exports = function(robot) {
  var cheerio, request;
  request = require('request');
  cheerio = require('cheerio');
  robot.respond(/(how full is garage)\s([a-zA-Z]+)\??/i, function(msg) {
    var r;
    return r = request('https://secure.parking.ucf.edu/GarageCount/iframe.aspx/', function(error, response, body) {
      var $, garage, garages, j, len, results;
      $ = cheerio.load(body);
      garages = [];
      $('.dxgvDataRow_DevEx').each(function(i, obj) {
        var html, j, len, line, percent, thisGarage;
        thisGarage = {};
        html = $(obj).html().replace(RegExp(' ', 'g'), '').split('\n');
        for (j = 0, len = html.length; j < len; j++) {
          line = html[j];
          if (line.startsWith("percent:")) {
            percent = parseInt(line.replace("percent:", ''));
            thisGarage.perc = percent;
          }
        }
        thisGarage.garage = ($(obj).find('.dxgv').html()).replace("Garage ", '');
        return garages[i] = thisGarage;
      });
      results = [];
      for (j = 0, len = garages.length; j < len; j++) {
        garage = garages[j];
        if (garage.garage.toLowerCase() === msg.match[2].toLowerCase()) {
          results.push(msg.send("Garage " + garage.garage + " is " + garage.perc + "% full"));
        } else {
          results.push(void 0);
        }
      }
      return results;
    });
  });
  robot.respond(/garage/i, function(msg) {
    var r;
    return r = request('https://secure.parking.ucf.edu/GarageCount/iframe.aspx/', function(error, response, body) {
      var $, garage, garages, j, len;
      $ = cheerio.load(body);
      garages = [];
      $('.dxgvDataRow_DevEx').each(function(i, obj) {
        var html, j, len, line, percent, thisGarage;
        thisGarage = {};
        html = $(obj).html().replace(RegExp(' ', 'g'), '').split('\n');
        for (j = 0, len = html.length; j < len; j++) {
          line = html[j];
          if (line.startsWith("percent:")) {
            percent = parseInt(line.replace("percent:", ''));
            thisGarage.perc = percent;
          }
        }
        thisGarage.garage = $(obj).find('.dxgv').html();
        return garages[i] = thisGarage;
      });
      response = "";
      for (j = 0, len = garages.length; j < len; j++) {
        garage = garages[j];
        response += garage.garage + "  " + garage.perc + "%\n";
      }
      return msg.send(response);
    });
  });
  return robot.respond(/where should I park?/i, function(msg) {
    var r;
    return r = request('https://secure.parking.ucf.edu/GarageCount/iframe.aspx/', function(error, response, body) {
      var $, garage, garages, j, len, smallestGarage;
      $ = cheerio.load(body);
      garages = [];
      $('.dxgvDataRow_DevEx').each(function(i, obj) {
        var html, j, len, line, percent, thisGarage;
        thisGarage = {};
        html = $(obj).html().replace(RegExp(' ', 'g'), '').split('\n');
        for (j = 0, len = html.length; j < len; j++) {
          line = html[j];
          if (line.startsWith("percent:")) {
            percent = parseInt(line.replace("percent:", ''));
            thisGarage.perc = percent;
          }
        }
        thisGarage.garage = ($(obj).find('.dxgv').html()).replace("Garage ", '');
        return garages[i] = thisGarage;
      });
      smallestGarage = {
        garage: "THEY'RE ALL FULL",
        perc: 100
      };
      for (j = 0, len = garages.length; j < len; j++) {
        garage = garages[j];
        if (garage.perc < smallestGarage.perc) {
          smallestGarage.garage = garage.garage;
          smallestGarage.perc = garage.perc;
        }
      }
      return msg.send("The most open garage is " + smallestGarage.garage + " which is " + smallestGarage.perc + "% full.");
    });
  });
};

// ---
// generated by coffee-script 1.9.2
